package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/mattboback/stageflow/clients/cli/internal/projectmode"
)

func newDocsCmd() *cobra.Command {
	var outDir string

	cmd := &cobra.Command{
		Use:                   "docs",
		Short:                 "Generate CLI documentation (Markdown)",
		DisableFlagsInUseLine: true,
		Args:                  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			targetDir, err := resolveDocsOutDir(outDir)
			if err != nil {
				return exitCodeError{Code: 2, Err: err}
			}

			err = os.MkdirAll(targetDir, 0o750)
			if err != nil {
				return exitCodeError{Code: 2, Err: fmt.Errorf("create out dir %s: %w", targetDir, err)}
			}

			err = doc.GenMarkdownTree(cmd.Root(), targetDir)
			if err != nil {
				return exitCodeError{Code: 2, Err: fmt.Errorf("generate docs: %w", err)}
			}

			err = scrubCobraDocFooters(targetDir)
			if err != nil {
				return exitCodeError{Code: 2, Err: fmt.Errorf("normalize docs: %w", err)}
			}

			return nil
		},
	}

	cmd.Flags().StringVar(
		&outDir,
		"out-dir",
		"docs/generated/cli",
		"Output directory (relative to repo root when in a git repo)",
	)

	return cmd
}

func resolveDocsOutDir(outDir string) (string, error) {
	raw := strings.TrimSpace(outDir)
	if raw == "" {
		return "", errors.New("--out-dir is required")
	}

	if filepath.IsAbs(raw) {
		return raw, nil
	}

	wd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("resolve working directory: %w", err)
	}

	gitRoot, ok, err := projectmode.FindGitRoot(wd)
	if err != nil {
		return "", err
	}

	if ok {
		return filepath.Join(gitRoot, raw), nil
	}

	return filepath.Join(wd, raw), nil
}

func scrubCobraDocFooters(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read docs dir %s: %w", dir, err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		if !strings.HasSuffix(name, ".md") {
			continue
		}

		path := filepath.Join(dir, name)

		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("read %s: %w", path, readErr)
		}

		lines := strings.Split(string(data), "\n")

		outLines := make([]string, 0, len(lines))
		for _, line := range lines {
			if strings.HasPrefix(line, "###### Auto generated by spf13/cobra") {
				continue
			}

			outLines = append(outLines, line)
		}

		normalized := strings.Join(outLines, "\n")
		if !strings.HasSuffix(normalized, "\n") {
			normalized += "\n"
		}

		// #nosec G703 -- path comes from os.ReadDir on the docs output directory.
		writeErr := os.WriteFile(path, []byte(normalized), 0o600)
		if writeErr != nil {
			return fmt.Errorf("write %s: %w", path, writeErr)
		}
	}

	return nil
}
