import type { ScanResults, ScannerMetadata } from './types';

export function buildStandaloneReportHTML(results: ScanResults, metadata: ScannerMetadata): string {
	const escape = (value: string): string =>
		value
			.replaceAll('&', '&amp;')
			.replaceAll('<', '&lt;')
			.replaceAll('>', '&gt;')
			.replaceAll('"', '&quot;')
			.replaceAll("'", '&#39;');

	const severityRows = Object.entries(results.summary.bySeverity)
		.map(([severity, count]) => `<tr><th scope="row">${escape(severity)}</th><td>${count}</td></tr>`)
		.join('');

	const pageRows = results.pages
		.map(
			(page) => `
          <tr>
            <td>${escape(page.pageId)}</td>
            <td><a href="${escape(page.url)}">${escape(page.url)}</a></td>
            <td>${page.issues.length}</td>
            <td>${page.success ? 'success' : 'failed'}</td>
          </tr>`
		)
		.join('');

	return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <title>StageFlow ${escape(metadata.name)} report</title>
    <style>
      :root {
        color-scheme: light;
        --bg: #f8fafc;
        --card: #ffffff;
        --ink: #0f172a;
        --muted: #475569;
        --accent: #0f766e;
        --border: #dbe4ee;
      }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: linear-gradient(180deg, #eff6ff 0%%, var(--bg) 45%%);
        color: var(--ink);
      }
      main {
        max-width: 1080px;
        margin: 0 auto;
        padding: 32px 20px 64px;
      }
      .hero, .card {
        background: var(--card);
        border: 1px solid var(--border);
        border-radius: 20px;
        box-shadow: 0 16px 40px rgba(15, 23, 42, 0.08);
      }
      .hero {
        padding: 28px;
        margin-bottom: 20px;
      }
      .eyebrow {
        display: inline-block;
        padding: 6px 10px;
        border-radius: 999px;
        background: #ccfbf1;
        color: #115e59;
        font-size: 12px;
        font-weight: 700;
        letter-spacing: 0.04em;
        text-transform: uppercase;
      }
      h1 {
        margin: 14px 0 10px;
        font-size: clamp(28px, 5vw, 42px);
        line-height: 1.05;
      }
      p { color: var(--muted); }
      .summary {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
        gap: 12px;
        margin-top: 20px;
      }
      .metric {
        padding: 16px;
        border-radius: 16px;
        background: #f8fafc;
        border: 1px solid var(--border);
      }
      .metric strong {
        display: block;
        font-size: 28px;
        margin-bottom: 4px;
      }
      .grid {
        display: grid;
        grid-template-columns: 1fr 1.4fr;
        gap: 20px;
      }
      .card {
        padding: 24px;
      }
      table {
        width: 100%%;
        border-collapse: collapse;
      }
      th, td {
        text-align: left;
        padding: 10px 12px;
        border-bottom: 1px solid var(--border);
        vertical-align: top;
      }
      th {
        font-size: 14px;
        color: var(--muted);
      }
      td a {
        color: var(--accent);
        text-decoration: none;
      }
      td a:hover {
        text-decoration: underline;
      }
      @media (max-width: 800px) {
        .grid {
          grid-template-columns: 1fr;
        }
      }
    </style>
  </head>
  <body>
    <main>
      <section class="hero">
        <span class="eyebrow">Scanner report</span>
        <h1>${escape(metadata.name)} findings for job ${escape(results.jobId)}</h1>
        <p>Generated by StageFlow Scanner Runner ${escape(metadata.version)}.</p>
        <div class="summary">
          <div class="metric"><strong>${results.summary.totalIssues}</strong><span>Total issues</span></div>
          <div class="metric"><strong>${results.summary.pagesScanned}</strong><span>Pages scanned</span></div>
          <div class="metric"><strong>${results.summary.pagesWithIssues}</strong><span>Pages with issues</span></div>
          <div class="metric"><strong>${results.durationMs} ms</strong><span>Duration</span></div>
        </div>
      </section>
      <section class="grid">
        <article class="card">
          <h2>Severity breakdown</h2>
          <table>
            <tbody>${severityRows}</tbody>
          </table>
        </article>
        <article class="card">
          <h2>Pages</h2>
          <table>
            <thead>
              <tr>
                <th>Page ID</th>
                <th>URL</th>
                <th>Issues</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>${pageRows}</tbody>
          </table>
        </article>
      </section>
    </main>
  </body>
</html>`;
}
