// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/playground": {
    params: {};
  };
  "/scan/:id": {
    params: {
      "id": string;
    };
  };
  "/scan/:id/report": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/playground" | "/scan/:id" | "/scan/:id/report" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/playground.tsx": {
    id: "routes/playground";
    page: "/playground";
  };
  "routes/scan.tsx": {
    id: "routes/scan";
    page: "/scan/:id";
  };
  "routes/scan-report.tsx": {
    id: "routes/scan-report";
    page: "/scan/:id/report";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/playground": typeof import("./app/routes/playground.tsx");
  "routes/scan": typeof import("./app/routes/scan.tsx");
  "routes/scan-report": typeof import("./app/routes/scan-report.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};