package orchestrator

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sort"

	"github.com/mattboback/stageflow/packages/shared-go/events"
	"github.com/mattboback/stageflow/packages/shared-go/models"
)

type completionError struct {
	Stage string
	Err   error
}

func (e *completionError) Error() string {
	if e == nil || e.Err == nil {
		return ""
	}

	return e.Err.Error()
}

func (e *completionError) Unwrap() error {
	if e == nil {
		return nil
	}

	return e.Err
}

func completionStage(err error) (string, error) {
	if err == nil {
		return "", nil
	}

	var cerr *completionError
	if errors.As(err, &cerr) {
		if cerr.Stage != "" {
			return cerr.Stage, cerr.Err
		}

		return events.JobFailStageReporting, cerr.Err
	}

	return events.JobFailStageReporting, err
}

func (o *Orchestrator) completeJobWithAggregatedResults(ctx context.Context, job *models.Job) error {
	if job.State == models.JobStateDone {
		slog.Debug("Job already completed", "job_id", job.ID)

		return nil
	}

	if job.State == models.JobStateFailed {
		slog.Debug("Job already failed, skipping completion", "job_id", job.ID)

		return nil
	}

	// Ensure we pass through COMPLETING for consistent lifecycle semantics (including partial-success).
	if job.State != models.JobStateCompleting {
		if !o.stateMachine.CanTransition(job.State, models.JobStateCompleting) {
			return fmt.Errorf("job %s cannot transition to COMPLETING from %s", job.ID, job.State)
		}

		if err := o.database.UpdateJobState(ctx, job.ID, models.JobStateCompleting); err != nil {
			return &completionError{Stage: events.JobFailStageReporting, Err: fmt.Errorf("failed to update job state to COMPLETING: %w", err)}
		}

		o.recordInternalEvent(ctx, job.ID, "orchestrator.state.transition", map[string]any{
			"from": string(job.State),
			"to":   string(models.JobStateCompleting),
		})

		job.State = models.JobStateCompleting
	}

	// Collect artifacts for each successful scanner. HTML reports are now
	// generated by the scan worker (scanner-runner) alongside results.json, so the
	// orchestrator no longer performs any report rendering here.
	var primaryReportPath, primaryStageLogPath, primaryRecipePath string

	scannerArtifacts := make(map[string]events.ScannerArtifacts)
	successfulScanners := make([]string, 0, len(job.ScannerResults))

	for scannerType, result := range job.ScannerResults {
		if !result.Success {
			continue
		}

		successfulScanners = append(successfulScanners, scannerType)

		// Use the report path produced by the scan worker (scanner-runner); do not attempt to
		// regenerate reports from results.json in the orchestrator.
		reportPath := result.ReportPath

		scannerArtifacts[scannerType] = events.ScannerArtifacts{
			ScannerType:  scannerType,
			ResultsPath:  result.ResultsPath,
			ReportPath:   reportPath,
			StageLogPath: result.StageLogPath,
			RecipePath:   result.RecipePath,
		}
	}

	primaryScanner, ok := o.selectPrimaryScanner(job, successfulScanners)
	if !ok {
		return errors.New("no successful scanner results found")
	}

	primaryResult := job.ScannerResults[primaryScanner]
	primaryReportPath = primaryResult.ReportPath
	primaryStageLogPath = primaryResult.StageLogPath
	primaryRecipePath = primaryResult.RecipePath

	reportJSONPath, err := o.buildAggregatedReport(ctx, job)
	if err != nil {
		return &completionError{Stage: "reporting", Err: err}
	}

	// Record scan completion time for metrics
	if err := o.database.RecordScanComplete(ctx, job.ID); err != nil {
		slog.Warn("Failed to record scan complete", "job_id", job.ID, "error", err)
	}

	var pagesScanned, totalIssues, criticalIssues, seriousIssues, moderateIssues, minorIssues int

	for _, result := range job.ScannerResults {
		if !result.Success {
			continue
		}

		pagesScanned += result.PagesScanned
		totalIssues += result.TotalIssues
		criticalIssues += result.CriticalIssues
		seriousIssues += result.SeriousIssues
		moderateIssues += result.ModerateIssues
		minorIssues += result.MinorIssues
	}

	if err := o.database.UpdateJobMetrics(ctx, job.ID, pagesScanned, totalIssues, criticalIssues, seriousIssues, moderateIssues, minorIssues); err != nil {
		slog.Warn("Failed to update job metrics", "job_id", job.ID, "error", err)
	}

	if err := o.database.CompleteJob(ctx, job.ID); err != nil {
		return &completionError{Stage: "completing", Err: fmt.Errorf("complete job in database: %w", err)}
	}

	job.State = models.JobStateDone

	if job.PodID != "" {
		if err := o.cleanupPod(ctx, job.PodID); err != nil {
			slog.Warn("Failed to cleanup pod", "pod_id", job.PodID, "error", err)
		}
	}

	o.cleanupVolumes(ctx, job.ID)
	o.cleanupStaging(ctx, job)

	payload := &events.JobCompletedPayload{
		JobID:  job.ID,
		Status: "success",
		Artifacts: events.ArtifactLocations{
			ReportJSON:     reportJSONPath,
			ReportHTML:     primaryReportPath,
			ScanStageLog:   primaryStageLogPath,
			ScanRecipe:     primaryRecipePath,
			ProvenanceJSON: job.ProvenanceKey,
		},
		ScannerArtifacts: scannerArtifacts,
	}

	if err := o.publisher.PublishJobCompleted(ctx, payload); err != nil {
		slog.Warn("Failed to publish job.completed event", "error", err)
		o.recordInternalEvent(ctx, job.ID, "orchestrator.event.publish_failed", map[string]any{
			"event": "job.completed",
			"error": err.Error(),
		})
	} else {
		o.recordInternalEvent(ctx, job.ID, "orchestrator.event.published", map[string]any{
			"event": "job.completed",
		})
	}

	scannerList := make([]string, 0, len(scannerArtifacts))
	for st := range scannerArtifacts {
		scannerList = append(scannerList, st)
	}

	slog.Info("Job completed successfully", "job_id", job.ID, "scanner_count", len(scannerArtifacts), "scanners", scannerList)

	return nil
}

func (o *Orchestrator) selectPrimaryScanner(job *models.Job, successfulScanners []string) (string, bool) {
	if len(successfulScanners) == 0 {
		return "", false
	}

	successSet := make(map[string]struct{}, len(successfulScanners))
	for _, scanner := range successfulScanners {
		successSet[scanner] = struct{}{}
	}

	for _, expected := range job.ExpectedScanners {
		if _, ok := successSet[expected]; ok {
			return expected, true
		}
	}

	sort.Strings(successfulScanners)

	return successfulScanners[0], true
}
