// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package scannermanifest

import (
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
)

type BrowserRequirement struct {
	// Args corresponds to the JSON schema field "args".
	Args []string `json:"args,omitempty"`

	// Headless corresponds to the JSON schema field "headless".
	Headless *bool `json:"headless,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type BrowserRequirementType `json:"type"`
}

type BrowserRequirementType string

const BrowserRequirementTypeChromium BrowserRequirementType = "chromium"
const BrowserRequirementTypeFirefox BrowserRequirementType = "firefox"
const BrowserRequirementTypeWebkit BrowserRequirementType = "webkit"

var enumValues_BrowserRequirementType = []interface{}{
	"chromium",
	"firefox",
	"webkit",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserRequirementType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BrowserRequirementType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BrowserRequirementType, v)
	}
	*j = BrowserRequirementType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BrowserRequirement) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in BrowserRequirement: required")
	}
	type Plain BrowserRequirement
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BrowserRequirement(plain)
	return nil
}

type ExternalTool struct {
	// Command corresponds to the JSON schema field "command".
	Command string `json:"command"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Optional corresponds to the JSON schema field "optional".
	Optional *bool `json:"optional,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version *string `json:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExternalTool) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["command"]; raw != nil && !ok {
		return fmt.Errorf("field command in ExternalTool: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ExternalTool: required")
	}
	type Plain ExternalTool
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.Command) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "command", 1)
	}
	if len(plain.Name) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = ExternalTool(plain)
	return nil
}

type IssueSeverity string

const IssueSeverityCritical IssueSeverity = "critical"
const IssueSeverityInfo IssueSeverity = "info"
const IssueSeverityMinor IssueSeverity = "minor"
const IssueSeverityModerate IssueSeverity = "moderate"
const IssueSeveritySerious IssueSeverity = "serious"

var enumValues_IssueSeverity = []interface{}{
	"critical",
	"serious",
	"moderate",
	"minor",
	"info",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IssueSeverity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IssueSeverity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IssueSeverity, v)
	}
	*j = IssueSeverity(v)
	return nil
}

type ManifestCapabilities struct {
	// Categories corresponds to the JSON schema field "categories".
	Categories []ScannerCategory `json:"categories"`

	// EstimatedTimePerPage corresponds to the JSON schema field
	// "estimatedTimePerPage".
	EstimatedTimePerPage *int `json:"estimatedTimePerPage,omitempty"`

	// MaxConcurrency corresponds to the JSON schema field "maxConcurrency".
	MaxConcurrency *int `json:"maxConcurrency,omitempty"`

	// OutputFormats corresponds to the JSON schema field "outputFormats".
	OutputFormats []OutputFormat `json:"outputFormats"`

	// RequiresBrowser corresponds to the JSON schema field "requiresBrowser".
	RequiresBrowser bool `json:"requiresBrowser"`

	// SupportsConcurrency corresponds to the JSON schema field "supportsConcurrency".
	SupportsConcurrency bool `json:"supportsConcurrency"`

	// SupportsOffline corresponds to the JSON schema field "supportsOffline".
	SupportsOffline *bool `json:"supportsOffline,omitempty"`

	// SupportsScreenshots corresponds to the JSON schema field "supportsScreenshots".
	SupportsScreenshots bool `json:"supportsScreenshots"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ManifestCapabilities) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["categories"]; raw != nil && !ok {
		return fmt.Errorf("field categories in ManifestCapabilities: required")
	}
	if _, ok := raw["outputFormats"]; raw != nil && !ok {
		return fmt.Errorf("field outputFormats in ManifestCapabilities: required")
	}
	if _, ok := raw["requiresBrowser"]; raw != nil && !ok {
		return fmt.Errorf("field requiresBrowser in ManifestCapabilities: required")
	}
	if _, ok := raw["supportsConcurrency"]; raw != nil && !ok {
		return fmt.Errorf("field supportsConcurrency in ManifestCapabilities: required")
	}
	if _, ok := raw["supportsScreenshots"]; raw != nil && !ok {
		return fmt.Errorf("field supportsScreenshots in ManifestCapabilities: required")
	}
	type Plain ManifestCapabilities
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Categories != nil && len(plain.Categories) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "categories", 1)
	}
	if plain.EstimatedTimePerPage != nil && 0 > *plain.EstimatedTimePerPage {
		return fmt.Errorf("field %s: must be >= %v", "estimatedTimePerPage", 0)
	}
	if plain.MaxConcurrency != nil && 1 > *plain.MaxConcurrency {
		return fmt.Errorf("field %s: must be >= %v", "maxConcurrency", 1)
	}
	if plain.OutputFormats != nil && len(plain.OutputFormats) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "outputFormats", 1)
	}
	*j = ManifestCapabilities(plain)
	return nil
}

// JSON Schema for SCANNER_OPTIONS validation
type ManifestConfigSchema interface{}

type ManifestEntry struct {
	// ExportName corresponds to the JSON schema field "exportName".
	ExportName *string `json:"exportName,omitempty"`

	// FactoryName corresponds to the JSON schema field "factoryName".
	FactoryName *string `json:"factoryName,omitempty"`

	// Module corresponds to the JSON schema field "module".
	Module string `json:"module"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ManifestEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["module"]; raw != nil && !ok {
		return fmt.Errorf("field module in ManifestEntry: required")
	}
	type Plain ManifestEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ExportName != nil && len(*plain.ExportName) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "exportName", 1)
	}
	if plain.FactoryName != nil && len(*plain.FactoryName) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "factoryName", 1)
	}
	if len(plain.Module) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "module", 1)
	}
	*j = ManifestEntry(plain)
	return nil
}

type ManifestOutput struct {
	// CategoryPrefix corresponds to the JSON schema field "categoryPrefix".
	CategoryPrefix *string `json:"categoryPrefix,omitempty"`

	// IncludeRawResults corresponds to the JSON schema field "includeRawResults".
	IncludeRawResults *bool `json:"includeRawResults,omitempty"`

	// ReportTemplate corresponds to the JSON schema field "reportTemplate".
	ReportTemplate *string `json:"reportTemplate,omitempty"`

	// SeverityMapping corresponds to the JSON schema field "severityMapping".
	SeverityMapping map[string]IssueSeverity `json:"severityMapping,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ManifestOutput) UnmarshalJSON(value []byte) error {
	type Plain ManifestOutput
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.CategoryPrefix != nil && len(*plain.CategoryPrefix) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "categoryPrefix", 1)
	}
	*j = ManifestOutput(plain)
	return nil
}

type ManifestRequirements struct {
	// Browser corresponds to the JSON schema field "browser".
	Browser *BrowserRequirement `json:"browser,omitempty"`

	// ExternalTools corresponds to the JSON schema field "externalTools".
	ExternalTools []ExternalTool `json:"externalTools,omitempty"`

	// Network corresponds to the JSON schema field "network".
	Network *NetworkRequirement `json:"network,omitempty"`

	// NodeVersion corresponds to the JSON schema field "nodeVersion".
	NodeVersion *string `json:"nodeVersion,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *ResourceRequirement `json:"resources,omitempty"`
}

type NetworkRequirement struct {
	// AllowedHosts corresponds to the JSON schema field "allowedHosts".
	AllowedHosts []string `json:"allowedHosts,omitempty"`

	// RequiresInternet corresponds to the JSON schema field "requiresInternet".
	RequiresInternet bool `json:"requiresInternet"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NetworkRequirement) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["requiresInternet"]; raw != nil && !ok {
		return fmt.Errorf("field requiresInternet in NetworkRequirement: required")
	}
	type Plain NetworkRequirement
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NetworkRequirement(plain)
	return nil
}

type OutputFormat string

const OutputFormatCsv OutputFormat = "csv"
const OutputFormatHtml OutputFormat = "html"
const OutputFormatJson OutputFormat = "json"

var enumValues_OutputFormat = []interface{}{
	"json",
	"html",
	"csv",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutputFormat) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OutputFormat {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OutputFormat, v)
	}
	*j = OutputFormat(v)
	return nil
}

type ResourceRequirement struct {
	// MaxMemoryMB corresponds to the JSON schema field "maxMemoryMB".
	MaxMemoryMB *int `json:"maxMemoryMB,omitempty"`

	// MaxTimeoutMs corresponds to the JSON schema field "maxTimeoutMs".
	MaxTimeoutMs *int `json:"maxTimeoutMs,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourceRequirement) UnmarshalJSON(value []byte) error {
	type Plain ResourceRequirement
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.MaxMemoryMB != nil && 1 > *plain.MaxMemoryMB {
		return fmt.Errorf("field %s: must be >= %v", "maxMemoryMB", 1)
	}
	if plain.MaxTimeoutMs != nil && 1 > *plain.MaxTimeoutMs {
		return fmt.Errorf("field %s: must be >= %v", "maxTimeoutMs", 1)
	}
	*j = ResourceRequirement(plain)
	return nil
}

type ScannerCategory string

const ScannerCategoryAccessibility ScannerCategory = "accessibility"
const ScannerCategoryCustom ScannerCategory = "custom"
const ScannerCategoryPerformance ScannerCategory = "performance"
const ScannerCategoryQuality ScannerCategory = "quality"
const ScannerCategorySecurity ScannerCategory = "security"
const ScannerCategorySeo ScannerCategory = "seo"

var enumValues_ScannerCategory = []interface{}{
	"accessibility",
	"performance",
	"security",
	"seo",
	"quality",
	"custom",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ScannerCategory) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ScannerCategory {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ScannerCategory, v)
	}
	*j = ScannerCategory(v)
	return nil
}

// Schema for defining Stageflow scanner plugins
type ScannerManifest struct {
	// Optional alternative identifiers/keywords for scanner resolution
	Aliases []string `json:"aliases,omitempty"`

	// Author corresponds to the JSON schema field "author".
	Author *string `json:"author,omitempty"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities ManifestCapabilities `json:"capabilities"`

	// ConfigSchema corresponds to the JSON schema field "configSchema".
	ConfigSchema ScannerManifestConfigSchema `json:"configSchema,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// Entry corresponds to the JSON schema field "entry".
	Entry ManifestEntry `json:"entry"`

	// Homepage corresponds to the JSON schema field "homepage".
	Homepage *string `json:"homepage,omitempty"`

	// Unique scanner identifier
	Id string `json:"id"`

	// License corresponds to the JSON schema field "license".
	License *string `json:"license,omitempty"`

	// Human-readable scanner name
	Name string `json:"name"`

	// Output corresponds to the JSON schema field "output".
	Output *ManifestOutput `json:"output,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository *string `json:"repository,omitempty"`

	// Requirements corresponds to the JSON schema field "requirements".
	Requirements *ManifestRequirements `json:"requirements,omitempty"`

	// Semantic version
	Version string `json:"version"`
}

type ScannerManifestConfigSchema interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ScannerManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["capabilities"]; raw != nil && !ok {
		return fmt.Errorf("field capabilities in ScannerManifest: required")
	}
	if _, ok := raw["entry"]; raw != nil && !ok {
		return fmt.Errorf("field entry in ScannerManifest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ScannerManifest: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ScannerManifest: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ScannerManifest: required")
	}
	type Plain ScannerManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Author != nil && len(*plain.Author) > 128 {
		return fmt.Errorf("field %s length: must be <= %d", "author", 128)
	}
	if plain.Description != nil && len(*plain.Description) > 500 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 500)
	}
	if plain.Homepage != nil && len(*plain.Homepage) > 256 {
		return fmt.Errorf("field %s length: must be <= %d", "homepage", 256)
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9-]*$`, string(plain.Id)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Id", `^[a-z][a-z0-9-]*$`)
	}
	if len(plain.Id) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 2)
	}
	if len(plain.Id) > 64 {
		return fmt.Errorf("field %s length: must be <= %d", "id", 64)
	}
	if plain.License != nil && len(*plain.License) > 64 {
		return fmt.Errorf("field %s length: must be <= %d", "license", 64)
	}
	if len(plain.Name) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if len(plain.Name) > 128 {
		return fmt.Errorf("field %s length: must be <= %d", "name", 128)
	}
	if plain.Repository != nil && len(*plain.Repository) > 256 {
		return fmt.Errorf("field %s length: must be <= %d", "repository", 256)
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$`, string(plain.Version)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Version", `^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$`)
	}
	*j = ScannerManifest(plain)
	return nil
}
