apiVersion: 1

datasources:
  - name: Orchestrator DB
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: false
